name: praca_inzynierska
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.5
  cached: ^1.3.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_serializable: ^6.5.4 
  freezed: ^2.2.0
  cached_network_image: ^3.2.3
  get_it: ^7.2.0
  injectable: 1.5.4
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  encrypted_shared_preferences: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_hooks: ^0.18.5+1
  theme_tailor_annotation: ^1.0.3
  hooked_bloc: ^1.2.1
  collection: ^1.16.0
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_auth: ^4.1.4
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  mockito: 5.3.2 
  mocktail: ^0.3.0
  fake_cloud_firestore: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: 1.5.5
  build_runner: ^2.3.0
  auto_route_generator: ^5.0.2
  retrofit_generator: ^4.2.0
  theme_tailor: ^1.0.8



flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/emoticons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
        - asset: assets/fonts/Mulish/Mulish-Light.ttf
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraLightItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-LightItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-Italic.ttf
        - asset: assets/fonts/Mulish/Mulish-MediumItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-BoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-BlackItalic.ttf
