name: praca_inzynierska
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: 3.0.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_bloc: 8.0.1
  equatable: 2.0.3
  easy_localization: 3.0.1
  dio: 4.0.6
  retrofit: 3.0.1+1
  json_serializable: 6.3.1
  freezed: 2.1.0+1
  cached_network_image: 3.2.1
  get_it: 7.2.0
  injectable: 1.5.3
  freezed_annotation: 2.1.0
  auto_route: 4.2.1
  shared_preferences: 2.0.15
  json_annotation: 4.6.0
  encrypted_shared_preferences: 3.0.1
  flutter_svg: 1.1.3
  readmore: 2.2.0
  flutter_hooks: 0.18.5+1
  theme_tailor_annotation: 1.0.3
  hooked_bloc: 1.2.0
  collection: 1.16.0
  html: 0.15.0
  mockito: 5.3.0
  rxdart: 0.27.5
  flutter_native_splash: 2.2.8
  flutter_launcher_icons: 0.10.0
  url_launcher: 6.1.5
  firebase_core: 2.3.0
  firebase_database: 10.0.2
  firebase_auth: 4.0.2
  google_sign_in: 5.4.2
  cloud_firestore: 4.1.0
  firebase_storage: 11.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  bloc_test: 9.0.3
  flutter_lints: 2.0.0
  injectable_generator: 1.5.4
  build_runner: 2.2.0
  auto_route_generator: 4.2.0
  retrofit_generator: 4.0.2
  pretty_dio_logger: 1.2.0-beta-1
  theme_tailor: 1.0.6



flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/emoticons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
        - asset: assets/fonts/Mulish/Mulish-Light.ttf
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraLightItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-LightItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-Italic.ttf
        - asset: assets/fonts/Mulish/Mulish-MediumItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-BoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBoldItalic.ttf
        - asset: assets/fonts/Mulish/Mulish-BlackItalic.ttf
